export const occupations = [
  { label: "Accountant" },
  { label: "Actor" },
  { label: "Administrator" },
  { label: "Architect" },
  { label: "Artist" },
  { label: "Astronaut" },
  { label: "Athlete" },
  { label: "Attorney" },
  { label: "Baker" },
  { label: "Barista" },
  { label: "Bartender" },
  { label: "Biologist" },
  { label: "Bookkeeper" },
  { label: "Builder" },
  { label: "Butcher" },
  { label: "Carpenter" },
  { label: "Cashier" },
  { label: "Chef" },
  { label: "Chemist" },
  { label: "Civil Engineer" },
  { label: "Cleaner" },
  { label: "Coach" },
  { label: "Computer Programmer" },
  { label: "Consultant" },
  { label: "Contractor" },
  { label: "Dancer" },
  { label: "Dentist" },
  { label: "Designer" },
  { label: "Detective" },
  { label: "Developer" },
  { label: "Doctor" },
  { label: "Driver" },
  { label: "Economist" },
  { label: "Electrician" },
  { label: "Engineer" },
  { label: "Entrepreneur" },
  { label: "Farmer" },
  { label: "Fashion Designer" },
  { label: "Firefighter" },
  { label: "Fisherman" },
  { label: "Flight Attendant" },
  { label: "Flight Instructor" },
  { label: "Florist" },
  { label: "Freelancer" },
  { label: "Gardener" },
  { label: "Geologist" },
  { label: "Graphic Designer" },
  { label: "Hairdresser" },
  { label: "Handyman" },
  { label: "Historian" },
  { label: "Housekeeper" },
  { label: "Human Resources Manager" },
  { label: "Illustrator" },
  { label: "Industrial Engineer" },
  { label: "Information Technology Specialist" },
  { label: "Inspector" },
  { label: "Instructor" },
  { label: "Interior Designer" },
  { label: "Interpreter" },
  { label: "Investigator" },
  { label: "Janitor" },
  { label: "Journalist" },
  { label: "Judge" },
  { label: "Laborer" },
  { label: "Landscape Architect" },
  { label: "Librarian" },
  { label: "Lifeguard" },
  { label: "Linguist" },
  { label: "Locksmith" },
  { label: "Machinist" },
  { label: "Manager" },
  { label: "Marketer" },
  { label: "Massage Therapist" },
  { label: "Mechanic" },
  { label: "Medical Assistant" },
  { label: "Medical Biller" },
  { label: "Medical Transcriptionist" },
  { label: "Mortician" },
  { label: "Musician" },
  { label: "Nanny" },
  { label: "Nurse" },
  { label: "Nutritionist" },
  { label: "Optometrist" },
  { label: "Painter" },
  { label: "Paralegal" },
  { label: "Paramedic" },
  { label: "Pastor" },
  { label: "Pediatrician" },
  { label: "Personal Trainer" },
  { label: "Pharmacist" },
  { label: "Photographer" },
  { label: "Physical Therapist" },
  { label: "Physician" },
  { label: "Pilot" },
  { label: "Plumber" },
  { label: "Police Officer" },
  { label: "Politician" },
  { label: "Professor" },
  { label: "Programmer" },
  { label: "Psychiatrist" },
  { label: "Psychologist" },
  { label: "Radiologist" },
  { label: "Real Estate Agent" },
  { label: "Receptionist" },
  { label: "Referee" },
  { label: "Reporter" },
  { label: "Researcher" },
  { label: "Salesperson" },
  { label: "Scientist" },
  { label: "Secretary" },
  { label: "Security Guard" },
  { label: "Social Worker" },
  { label: "Software Developer" },
  { label: "Speech Therapist" },
  { label: "Statistician" },
  { label: "Stylist" },
  { label: "Surgeon" },
  { label: "Surveyor" },
  { label: "Tailor" },
  { label: "Teacher" },
  { label: "Technician" },
  { label: "Veterinarian" },
  { label: "Waiter" },
  { label: "Waitress" },
  { label: "Welder" },
  { label: "Writer" },
];
